version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Test
          command: "cargo test"
      - codecov/upload:
          file: ./coverage/lcov.info
