version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  rust: circleci/rust@1.6.0

workflows:
  production:
    jobs:
      - rust/lint-test-build:
          release: true

  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
