version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - checkout
      - run: cargo --version
      - run:
        name: Test
        command: "cargo test"
jobs:
  build:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - checkout
      - run: cargo --version
